#=========================== Filebeat prospectors =============================
filebeat.prospectors:
- input_type: log
  paths:
    - C:\optiLogs\*\*.log

  harvester_buffer_size: 655360
  max_bytes: 10485760
fields:
  PRIVATE_KEY: "Key"
  COMPANY_ID: "ComId"
  APP_NAME: "App"
  SUB_SYSTEM: "Subsystem"

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstashserver.coralogix.com:5015"]
  index: logstash
  tls.certificate_authorities: ["C:/Filebeat/ca.crt"]
  ssl.certificate_authorities: ["C:/Filebeat/ca.crt"]
  # hosts: ["logstashserver.coralogix.com:5044"]

