#=========================== Filebeat prospectors =============================
filebeat.prospectors:
- input_type: log
  paths:
    - C:\Optimove\Source\Repos\ExplorationEngine\*\Logs\*.log

  harvester_buffer_size: 655360
  max_bytes: 10485760
fields:
  PRIVATE_KEY: "PRIVATE_KEY"
  COMPANY_ID: "COMPANzxsdfvsadzfsfdY_ID"
  APP_NAME: "APP_NAME"
  SUB_SYSTEM: "SUB_SYSTEM"

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstashserver.coralogix.com:5044"]
